### ISSUE TITLE
Specifying Index in search query

### ISSUE THREAD

**Issue by tom-w-tdy-ansarda** [vinted/elasticsearch-dsl-rs#112]
Hiya!

Library looks fantastic!

Was just wondering if there's some way to limit a query to a specific index?
Similar to how the elastic-search rs library accepts an index-id:
```rust
es_client.search(SearchParts::Index(&[&index_id]))
               .from(0)
               // etc etc
```

**Comment by buinauskas** [comment]
@tom-w-tdy-ansarda sorry I didn't reply earlier, it totally slipped through the notifications!

Unfortunately this library operates only at the payload level and index is part of the URL, so your snippet is the right way of doing things.
