### ISSUE TITLE
Implement script_fields for Search

### ISSUE THREAD

**Issue by mtorromeo** [vinted/elasticsearch-dsl-rs#217]
Hi,
I don't see any obvious way to use [script_fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#script-fields) and it's the only feature I am missing.

Thanks

**Comment by buinauskas** [comment]
Hello, thanks for your report. I'll look into it this week.

**Comment by buinauskas** [comment]
I've implemented both this and https://github.com/vinted/elasticsearch-dsl-rs/issues/218 and released with version 0.4.14. Please report if something is not as expected.

**Comment by mtorromeo** [comment]
Awesome, thank you! I'll probably test this next week.
Cheers
