### ISSUE TITLE
Comment //TODO

### ISSUE THREAD

**Issue by FrederickFrance** [vinted/elasticsearch-dsl-rs#228]
Hi,

I see
```
impl SpanNearQuery {
    /// TODO
    pub fn in_order(mut self, in_order: bool) -> Self {
        self.in_order = Some(in_order);
        self
    }

    /// TODO
    pub fn slop(mut self, slop: i32) -> Self {
        self.slop = Some(slop);
        self
    }
}
```

How does the TODO mean ? "TODO a comment for the function" ?

Thanks for this crate but I think that it is sorely lacking in comments.

**Comment by buinauskas** [comment]
Hello, thanks for the report!

This is something that slipped through, these TODOs are missing documentation comments. I'll add them.

**Comment by buinauskas** [comment]
@FrederickFrance I did update these comments, is there anything else you'd want me to fix?

**Comment by FrederickFrance** [comment]
> @FrederickFrance I did update these comments, is there anything else you'd want me to fix?

I planned to open another issue, but, as you're asking, I'm asking here.

I cannot do : 
```
pub fn transform(input : MyInput/* whatever */) -> anyhow::Result<BoolQuery> {
    let mut result = Query::bool();

    for i in input.a_vec {
        if let Some(c) = i.crab
        {
            let must = Query::bool()
                    .should(
                        Query::bool().must(
                            Query::multi_match(
                                [
                                    "Hello",
                                    "world",
                                ],
                                c,
                            )
                            .r#type(TextQueryType::Phrase),
                        ),
                    )
                    .should(Query::range("abc").gte(4))
                    .should(Query::bool().must_not(Query::exists("abc")));
                result.must(must.clone());
            }        
    }

    return Ok(result);
}
```

 **|     let mut result = Query::bool();
   |         ---------- move occurs because `result` has type `elasticsearch_dsl::BoolQuery`, which does not implement the `Copy` trait
 |
 |     for concept in front_input.concepts.unwrap_or_default() {
   |     ------------------------------------------------------- inside of this loop
...
 |                 result.must(must.clone());
   |                 ^^^^^^ value moved here, in previous iteration of loop**

Could you help me or fix something ?

Thanks

**Comment by buinauskas** [comment]
```rs
pub fn transform(input : MyInput/* whatever */) -> anyhow::Result<BoolQuery> {
    let mut result = Query::bool();

    for i in input.a_vec {
        if let Some(c) = i.crab {
            let must = Query::bool()
                    .should(
                        Query::bool().must(
                            Query::multi_match(
                                [
                                    "Hello",
                                    "world",
                                ],
                                c,
                            )
                            .r#type(TextQueryType::Phrase),
                        ),
                    )
                    .should(Query::range("abc").gte(4))
                    .should(Query::bool().must_not(Query::exists("abc")));
                result = result.must(must);
            }        
    }

    return Ok(result);
}
```

This is not really an issue with the DSL but with the way Rust works. This will at least compile.

**Comment by FrederickFrance** [comment]
Right
My real function is more complicated, so this example is not good

**Comment by buinauskas** [comment]
@FrederickFrance I'll close the issue then, You're really dealing with Rust's ownership issues rather than the issues with this crate right now.
