### ISSUE TITLE
Point in time

### ISSUE THREAD

**Issue by FrederickFrance** [vinted/elasticsearch-dsl-rs#233]
Hi,

I'm trying to use PIT but I don't find how to do.

My code is similar as :

```
let client = Elasticsearch::default();
let s = client.search(SearchParts::None).size(1000).timeout("120s");
let search = Search::new().query(my_bool_query);
let response = s.body(json!(search)).allow_no_indices(true).send().await?;
```

What I understand : 
- if I want to use a scroll, I can write let s = client.search(SearchParts::None).scroll("100s").size(1000).timeout("120s"); (and close it later)
- if I want to open or close a point in time, I can open and close one.

I don't understand how to add the pit id in the search.

**Comment by buinauskas** [comment]
Hi, this is only library for the DSL construction, please forward questions related to the official Elasticsearch Rust client to https://github.com/elastic/elasticsearch-rs

Thank you.
