### ISSUE TITLE
HasChildQuery mistake in documentation

### ISSUE THREAD

**Issue by FrederickFrance** [vinted/elasticsearch-dsl-rs#235]
Hi

I notice [HasChildQuery](https://github.com/vinted/elasticsearch-dsl-rs/blob/master/src/search/queries/joining/has_child_query.rs) has a doc comment link to missing link. [query-dsl-HasChild-query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-HasChild-query.html) should be replace by [query-dsl-has-child-query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html)

Regards

**Comment by buinauskas** [comment]
Hi, I would appreciate if you could submit a pull request for that 🙏🏻 thank you!

**Comment by FrederickFrance** [comment]
I try to do that today

**Comment by FrederickFrance** [comment]
Done https://github.com/vinted/elasticsearch-dsl-rs/pull/237

**Comment by FrederickFrance** [comment]
And this one for clippy
https://github.com/vinted/elasticsearch-dsl-rs/pull/241
