### ISSUE TITLE
HasChildQuery inner_hits

### ISSUE THREAD

**Issue by FrederickFrance** [vinted/elasticsearch-dsl-rs#236]
Hi

If I understand well, I could add a inner_hits on a HasChildQuery 

> Inner hits can be used by defining an inner_hits definition on a nested, has_child or has_parent query and filter.

https://www.elastic.co/guide/en/elasticsearch/reference/current/inner-hits.html

But I don't understand how to do.

```
let q = Query::has_child(
        "tag",
        Query::bool()
            .filter([Query::term("a", "b")])
            .filter(Query::terms("def", ["g", "h"])),
    );

```

Is it missing or I do a mistake ?

**Comment by buinauskas** [comment]
I think you should be able to, at least looking at the documentation. I'll fix this by the end of the week. Thanks!

**Comment by buinauskas** [comment]
Closing, will release sometime soon.
