### ISSUE TITLE
Aggregation is complex

### ISSUE THREAD

**Issue by FrederickFrance** [vinted/elasticsearch-dsl-rs#238]
Hi

Aggregations are very blurred in my mind.

I'm trying to do : 
```
 "aggs": {
    "timeline": {
      "date_histogram": {
        "field": "audit_date",
        "calendar_interval": "month",
        "min_doc_count": 1,
        "time_zone": "+02:00"
      }
    }
  }
```

But I don't understand how to do :cry: 

Regards

**Comment by buinauskas** [comment]
Hi, DSL does not yet support all of the aggs, I have minimal time supporting the DSL and mostly add them on demand. I'll try implementing this as well.
