### ISSUE TITLE
SortSpecialField

### ISSUE THREAD

**Issue by FrederickFrance** [vinted/elasticsearch-dsl-rs#249]
Hi

"_id" should be included in SortSpecialField, right ?

**Comment by buinauskas** [comment]
I do not remember anymore, these are special as in they are reserved and you cannot provide anything extra to them. You can perfectly use the `_id` field with asc/desc order the way you want using the regular `SortField`.

**Comment by FrederickFrance** [comment]
you mean the regular `FieldSort` ?

**Comment by buinauskas** [comment]
Yes, that.
